# -*- coding: utf-8 -*-
"""falskserverforcustomersupport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_ubOjb02ZGN24eGGSdFX-DbD-KcINmR
"""

!pip install flask
!pip install pyngrok

from flask import Flask, request, jsonify
from pyngrok import ngrok, conf
import joblib

# Set ngrok authtoken
conf.get_default().auth_token = "2kcEgu8zdl5no1qL4N1SXlaTnBL_FJb14mK9Nbn4prp9uVyu"

# Load your model and vectorizer
model = joblib.load('/content/best_complaint_model.pkl')
vectorizer = joblib.load('/content/vectorizer.pkl')

# Create Flask app
app = Flask(__name__)

label_map = {
    0: 'Bank Account services',
    1: 'Credit card or prepaid card',
    2: 'Others',
    3: 'Theft/Dispute Reporting',
    4: 'Mortgage/Loan'
}

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        text = data.get("text", "")
        text_vector = vectorizer.transform([text])
        pred_class = model.predict(text_vector)[0]
        pred_label = label_map.get(pred_class, "Unknown")
        return jsonify({'prediction': pred_label})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# Start ngrok tunnel
public_url = ngrok.connect(5000)
print(f"🔗 Public URL: {public_url}")

# Run Flask app
app.run()



